# == Gitlab CI/CD quickstart
# https://docs.gitlab.com/ee/ci/quick_start/README.html
# == Gitlab yml file config reference ==
# https://docs.gitlab.com/ee/ci/yaml/
# == DPL deployment tool docs ==
# https://docs.gitlab.com/ee/ci/examples/deployment/README.html
# == Based upon Gitlab Python Heroku deployment example ==
# https://docs.gitlab.com/ee/ci/examples/test-and-deploy-python-application-to-heroku.html

stages:
  - deploy

production:
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=devops-rabbitmq --api-key=$HEROKU_PRODUCTION_API_KEY
  only:
    - master
# Deploying with Docker
# https://devcenter.heroku.com/categories/deploying-with-docker
# Decided to build images because cannot be bothered to pre-build and upload to cloud in CI/CD
# On Docker compose files
# https://stackoverflow.com/questions/46904060/how-to-push-docker-containers-managed-by-docker-compose-to-heroku
# Docker swarm instead of docker compose
# https://stackoverflow.com/questions/49999920/docker-compose-heroku-hostname-links-and-production-deployment
# Addon that manages the swarm
# https://devcenter.heroku.com/articles/dockhero
