version: '3.2'
services:
  go:
    build: ./src/go-server
    image: go-server
    #using ports will expose the service to host machine
    ports:
      - 8080:8080
    networks:
      - ping-network
  node:
    build: ./src/node-server
    image: node-server
    # using expose only exposes the container in docker network
    expose: 
      - "8081"
    # depends_on:
      # - postgres
    networks:
      - ping-network
    # environment:
    # volumes:
networks:
  ping-network:

# volumes:

