# https://stackoverflow.com/questions/31746182/docker-compose-wait-for-container-x-before-starting-y
  # https://stackoverflow.com/questions/47710767/what-is-the-alternative-to-condition-form-of-depends-on-in-docker-compose-versio
  # https://stackoverflow.com/questions/57065750/docker-compose-volume-overrides-copy-in-multi-stage-build
  # on-failure https://docs.docker.com/config/containers/start-containers-automatically/#use-a-restart-policy

version: '3.2'
services:
  rabbit:
    image: rabbitmq:3-management
    expose: 
      - "5672"
    # For debugging and development to access rabbit in local network
    # ports:  
    # - "15672:15672"
    # - "5672:5672"
    networks:
      - rabbit-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://rabbit:15672"]
      interval: 5s
      timeout: 3s
      retries: 3
  orig:
    build: ./src/orig
    command: yarn start
    image: orig
    # The rabbit startup will take some time in which time the initializations
    # will fail, since we cannot wait for the health check to pass in 
    # docker-compose version 3+ we'll just restart on failure
    restart: always
    environment: 
      - ENV=docker 
    depends_on:
      - rabbit
    networks:
      - rabbit-network
  obse:
    build: ./src/obse
    command: yarn start
    image: obse
    # https://docs.docker.com/compose/environment-variables/
    environment: 
      - ENV=docker
    restart: always
    depends_on:
      - rabbit
    networks:
      - rabbit-network
    volumes: 
      - data:/home/node/data/
  imed:
    build: ./src/imed
    command: yarn start
    image: imed
    restart: always
    environment: 
      - ENV=docker
    depends_on:
      - rabbit
    networks:
      - rabbit-network
  httpserv:
    build: ./src/httpserv
    command: yarn start
    image: httpserv
    ports:  
      - 8080:8080
    restart: always
    depends_on:
      - rabbit
    networks:
      - rabbit-network
    volumes: 
      - data:/home/node/data/
networks:
  rabbit-network:
volumes:
  data:
