version: '3.2'
services:
  # https://stackoverflow.com/questions/31746182/docker-compose-wait-for-container-x-before-starting-y
  # https://stackoverflow.com/questions/47710767/what-is-the-alternative-to-condition-form-of-depends-on-in-docker-compose-versio
  # https://stackoverflow.com/questions/57065750/docker-compose-volume-overrides-copy-in-multi-stage-build
  rabbit:
    image: rabbitmq:3-management
    #using ports will expose the service to host machine
    # expose: 
    #   - "5672"
    ports:  
    - "15672:15672"
    - "5672:5672"
    networks:
      - rabbit-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://rabbit:15672"]
      interval: 3s
      timeout: 1s
      retries: 3
  orig:
    build: ./src/orig
    command: yarn start
    image: orig
    restart: always # on-failure https://docs.docker.com/config/containers/start-containers-automatically/#use-a-restart-policy
    depends_on:
      - rabbit
    networks:
      - rabbit-network
  obse:
    build: ./src/obse
    command: yarn start
    image: obse
    restart: always
    depends_on:
      - rabbit
    networks:
      - rabbit-network
    volumes: 
      - data:/home/node/data/
      - ./src/obse/:/home/node/app/
  imed:
    build: ./src/imed
    command: yarn start
    image: imed
    restart: always
    depends_on:
      - rabbit
    networks:
      - rabbit-network
  httpserv:
    build: ./src/httpserv
    command: yarn start
    image: httpserv
    # using expose only exposes the container in docker network
    ports:  
      - 8080:8080
    restart: on-failure
    depends_on:
      - rabbit
    networks:
      - rabbit-network
    volumes: 
      - data:/home/node/data/
      - ./src/httpserv/:/home/node/app/
networks:
  rabbit-network:
volumes:
  data:
